[package]
name = "tools"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.47"
lexopt = "0.2.0"
xshell = "0.2"
serde_json = "1.0"
reqwest = { version = "0.11.12", features = ["blocking"] }
scraper = "0.13.0"
